version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./dockerfile.gpu
    tty: true
    volumes:
      - ./book/:/app/book
      - ./notebooks/:/app/notebooks
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "$JUPYTER_PORT:$JUPYTER_PORT"
    env_file:
      - ./.env
    entrypoint: jupyter lab --ip 0.0.0.0 --port=8888 --no-browser --allow-root
